id: P010548
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00EGS1016943
  title: དགག་ལན་མུན་སེལ་སྒྲོན་མེ་ལ་རྣམ་པར་དཔྱད་པ་ལོག་རྟོག་ཉེས་རྡུལ་སྤྲུག་པའི་རྔ་ཡབ
  author: ''
  volumes:
    b35129ab7fb2444a8ecc6214df060cce:
      image_group_id: I01JW240
      title: ''
      volume_number: 1
      total_pages: 196
      base_file: v001.txt
